# -*- coding: utf-8 -*-
"""Uber_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mK1VzK6vHIk4N7aStRpfRbbkSjuaj7hn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

df=pd.read_csv('/content/City.csv')
df.head(5)

# checking null value & duplicates in city data set and remove them
df.isnull().sum()
df.dropna(inplace=True)
df.isnull().sum()
df.info()

df.duplicated().sum()
df.drop_duplicates(inplace=True)
df.duplicated().sum()

#convert values decimal to round
df['avg_fare']=df['avg_fare'].round(2)
df['avg_wait_time_min']=df['avg_wait_time_min'].round(2)
df.head()

# download data set


df.to_csv('city_data.csv', index = False)

files.download('city_data.csv')

df1=pd.read_csv('/content/Drivers.csv')
df1.head()

# checking null value & duplicates in drivers data set and remove them
df1.isnull().sum()
df1.dropna(inplace=True)
df1.isnull().sum()

df1.duplicated().sum()

# convert all decimal vlaues in round (2)
df1.columns
df1=pd.read_csv('/content/Drivers.csv').applymap(lambda x: f"{x:.2f}" if isinstance(x,float) else x)
df1.head()

df1.to_csv('drivers_dat.csv',index = False)
files.download('drivers_dat.csv')

df3=pd.read_csv('/content/Rides.csv')
df3.head()

df3.isnull().sum()
df3.dropna(inplace=True)
df3.isnull().sum()

df3.duplicated().sum()

df3.columns
df3['distance_km']= df3['distance_km'].round(2)
df3['fare']= df3['fare'].round(2)
df3.head()

df3.to_csv('rides_dataset.csv',index=False)
files.download('rides_dataset.csv')

df4=pd.read_csv('/content/payments_data.csv')
df4.head()
df4.isnull().sum()
df4.dropna(inplace=True)
df4.isnull().sum()

df4.columns
df4['fare']= df4['fare'].round(2)
df4['driver_earnings']=df4['driver_earnings'].round(2)
df4['surge_multiplier']=df4['surge_multiplier'].round(2)
df4['uber_commission']=df4['uber_commission'].round(2)
df4.head()

df4.to_csv('payments_dats.csv',index = False)
files.download('payments_dats.csv')